---
# tasks file for swarm

- name: Create Swarm Service
  command: docker service create --label traefik.port=80 --label traefik.frontend.rule=Host:{{domain}} --network {{traefik_network}} --name={{domain_name}} --mount=type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock --mount=type=bind,src=/var/www/html/{{domain}},dst=/usr/html --env=VIRTUAL_HOST={{domain}} yobasystems/alpine-php-wordpress
