---
# tasks file for mysql
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Install required software
  apt: name={{ item }} state=present 
  with_items:
    - mysql-server
    - python-mysqldb

- name: Create mysql database
  mysql_db: name={{ wp_mysql_db }} state=present login_password={{ root_mysql_password }}

- name: Create mysql user
  mysql_user: 
    login_password={{ root_mysql_password }}
    name={{ wp_mysql_user }} 
    password={{ wp_mysql_password }} 
    priv={{ wp_mysql_db }}.*:ALL
