---
# tasks file for php
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - php7.0-mysql
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-mcrypt
    - python-mysqldb
